package repositories

import (
	"context"
	"fmt"
	domain "parser/internal/domain/models"
	"parser/internal/postgres"

	sq "github.com/Masterminds/squirrel"
)

type AdvertRepository interface {
	Insert(ctx context.Context, ad *domain.Advert) error
	Update(ctx context.Context, ad *domain.Advert) error
	GetByURL(ctx context.Context, url string) (*domain.Advert, error)
}

type advertRepo struct {
	db *postgres.Postgres
}

func NewAdvertRepo(db *postgres.Postgres) AdvertRepository {
	return &advertRepo{db: db}
}

func (s *advertRepo) GetByURL(ctx context.Context, url string) (*domain.Advert, error) {
	sql, args, err := sq.Select("*").
		From("adverts").
		Where("url = $1", url).
		PlaceholderFormat(sq.Dollar).
		ToSql()

	if err != nil {
		return nil, err
	}

	rows, release, err := s.db.Query(ctx, sql, args)
	if err != nil {
		return nil, err
	}

	defer release()

	var ad domain.Advert

	err = s.db.ScanOne(rows, &ad)
	if err != nil {
		return nil, postgres.CheckEmptyRows(err)
	}

	return &ad, nil
}

func (s *advertRepo) Insert(ctx context.Context, ad *domain.Advert) error {
	// When firstly inserted other fields but url are autogenerated
	sql, args, err := sq.Insert("adverts").
		Columns("advert_id", "url").
		Values(ad.AdvertID, ad.URL).
		PlaceholderFormat(sq.Dollar).
		ToSql()

	if err != nil {
		return err
	}

	_, release, err := s.db.Exec(ctx, sql, args)
	if err != nil {
		return err
	}

	defer release()

	return nil
}

func (s *advertRepo) Update(ctx context.Context, ad *domain.Advert) error {

	sql, args := sq.Update("adverts").
		Set("current_price", ad.CurrentPrice()).
		Set("last_price", ad.LastPrice()).
		Set("title", ad.Title()).
		Where(sq.Eq{
			"advert_id": ad.AdvertID,
		}).
		MustSql()

	fmt.Println(sql)
	_, release, err := s.db.Exec(ctx, sql, args)
	if err != nil {
		return err
	}

	defer release()

	return nil
}
