linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - exhaustive
    - gocritic
    - goimports
    - importas
    - nakedret
    - noctx
    - prealloc
    - predeclared
    - wsl
output:
  format: json
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
