version: "3.8"

services:
  migrations:
    image: migrate/migrate
    volumes:
      - ../migrations:/migrations/
    command:
      ["-database", "${DB_URL}", "-path", "/migrations", "-verbose", "down", "-all"]
