version: "3.8"

services:
  avito-parser:
    build:
      context: "../"
      dockerfile: "./docker/dev.Dockerfile"
    environment:
       - DB_URL
       - BOT_TOKEN
       - ADDR
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
